spring:
  config:
    activate:
      on-profile:
  jpa:
    hibernate:
      ddl-auto: validate # create update create-update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: ""
