export const Grass = () => {
  return (
    <>
      <svg className="w-full h-[200px]" viewBox="0 0 1120 180">
        <text
          fontSize="13"
          textAnchor="start"
          x="1020"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          12월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="940"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          11월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="840"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          10월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="760"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          9월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="680"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          8월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="580"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          7월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="500"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          6월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="400"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          5월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="320"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          4월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="240"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          3월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="160"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          2월
        </text>
        <text
          fontSize="13"
          textAnchor="start"
          x="60"
          y="160"
          dy="0.3em"
          fill="#8a8f95"
        >
          2022
        </text>
        <rect
          width="18"
          height="18"
          x="1100"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1100"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1100"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1100"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1100"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1100"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1080"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1060"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1040"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1020"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="1000"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="980"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="60"
          rx="5"
          fill="#78cb94"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="960"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="940"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="920"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="900"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="880"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="120"
          rx="5"
          fill="#007950"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="100"
          rx="5"
          fill="#78cb94"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="80"
          rx="5"
          fill="#a1e4ac"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="60"
          rx="5"
          fill="#4eb17c"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="40"
          rx="5"
          fill="#007950"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="860"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="840"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="820"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="800"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="780"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="760"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="740"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="720"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="700"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="680"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="660"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="640"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="620"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="600"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="580"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="560"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="540"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="520"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="500"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="480"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="460"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="440"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="420"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="400"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="380"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="360"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="340"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="320"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="300"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="280"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
          stroke="transparent"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="260"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="240"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="220"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="200"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="180"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="160"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="140"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="120"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="100"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="80"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="60"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="40"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="20"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="80"
          y="0"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="60"
          y="120"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          width="18"
          height="18"
          x="60"
          y="100"
          rx="5"
          fill="#dddfe0"
          strokeWidth="2.5"
        ></rect>
        <rect
          pointerEvents="none"
          width="200"
          height="30"
          rx="5"
          fill="#000000"
          display="none"
          x="552"
          y="64"
        ></rect>
      </svg>
    </>
  );
};
